"""initial schema

Revision ID: 5cdc2a363713
Revises: 
Create Date: 2026-09-19 12:16:25.486808
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5cdc2a363713'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES = (
    "user_role", "class_status", "document_status", "content_status", "session_status", "item_type",
    "review_status", "session_mode", "progress_status", "xp_reason", "request_status", "agent_run_status",
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_model', sa.String(length=128), nullable=False),
    sa.Column('artifact_uri', sa.String(length=1024), nullable=True),
    sa.Column('quantization', sa.String(length=32), nullable=True),
    sa.Column('eval_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', name=op.f('uq_model_versions_name'))
    )
    op.create_index('uq_model_versions_active', 'model_versions', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('trainee', 'trainer', 'developer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('classes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('initial_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='class_status'), server_default='draft', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('initial_xp >= 0', name=op.f('ck_classes_initial_xp_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_classes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_classes_trainer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_trainer_id'), 'classes', ['trainer_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('class_access_codes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_access_codes_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_class_access_codes_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_access_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_class_access_codes_code'))
    )
    op.create_index(op.f('ix_class_access_codes_class_id'), 'class_access_codes', ['class_id'], unique=False)
    op.create_table('class_members',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_members_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_class_members_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_class_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'user_id', name=op.f('pk_class_members'))
    )
    op.create_index(op.f('ix_class_members_user_id'), 'class_members', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='document_status'), server_default='uploaded', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_documents_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_class_id'), 'documents', ['class_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='session_status'), server_default='draft', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_training_sessions_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_training_sessions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions'))
    )
    op.create_index(op.f('ix_training_sessions_class_id'), 'training_sessions', ['class_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='agent_run_status'), server_default='queued', nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_agent_runs_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_agent_runs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_agent_runs_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent'), 'agent_runs', ['agent'], unique=False)
    op.create_table('topics',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_topics_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_topics_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_class_id'), 'topics', ['class_id'], unique=False)
    op.create_table('content_documents',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('additional_info_markdown', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), server_default='draft', nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_content_documents_edited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_content_documents_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_content_documents_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_documents')),
    sa.UniqueConstraint('topic_id', 'version', name=op.f('uq_content_documents_topic_id'))
    )
    op.create_table('content_requests',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('triage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'fulfilled', 'rejected', name='request_status'), server_default='open', nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_content_requests_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_content_requests_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_content_requests_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_content_requests_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_requests'))
    )
    op.create_index(op.f('ix_content_requests_class_id'), 'content_requests', ['class_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_document_chunks_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'position', name=op.f('uq_document_chunks_document_id'))
    )
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_topic_id'), 'document_chunks', ['topic_id'], unique=False)
    op.create_table('session_items',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('content', 'quiz', 'poll', name='item_type'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('review_status', sa.Enum('generated', 'approved', 'edited', 'rejected', name='review_status'), server_default='generated', nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type <> 'quiz' OR correct_option IS NOT NULL", name=op.f('ck_session_items_quiz_has_answer')),
    sa.CheckConstraint("item_type = 'content' OR (question IS NOT NULL AND options IS NOT NULL)", name=op.f('ck_session_items_question_items_have_options')),
    sa.CheckConstraint('time_limit_seconds IS NULL OR time_limit_seconds > 0', name=op.f('ck_session_items_time_limit_positive')),
    sa.CheckConstraint('xp_reward >= 0', name=op.f('ck_session_items_xp_reward_non_negative')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_session_items_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_session_items_session_id_training_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_session_items_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_items')),
    sa.UniqueConstraint('session_id', 'position', name=op.f('uq_session_items_session_id'))
    )
    op.create_table('live_runs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('current_item_id', sa.UUID(), nullable=True),
    sa.Column('item_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['current_item_id'], ['session_items.id'], name=op.f('fk_live_runs_current_item_id_session_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_live_runs_session_id_training_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_live_runs_started_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_runs'))
    )
    op.create_index(op.f('ix_live_runs_session_id'), 'live_runs', ['session_id'], unique=False)
    op.create_table('session_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mode', sa.Enum('live', 'self_paced', name='session_mode'), nullable=False),
    sa.Column('current_item_id', sa.UUID(), nullable=True),
    sa.Column('completed_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='progress_status'), server_default='in_progress', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['current_item_id'], ['session_items.id'], name=op.f('fk_session_progress_current_item_id_session_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_session_progress_session_id_training_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_progress')),
    sa.UniqueConstraint('user_id', 'session_id', 'attempt', name=op.f('uq_session_progress_user_id'))
    )
    op.create_index(op.f('ix_session_progress_session_id'), 'session_progress', ['session_id'], unique=False)
    op.create_table('responses',
    sa.Column('session_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('live_run_id', sa.UUID(), nullable=True),
    sa.Column('chosen_option', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['live_run_id'], ['live_runs.id'], name=op.f('fk_responses_live_run_id_live_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progress_id'], ['session_progress.id'], name=op.f('fk_responses_progress_id_session_progress'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_item_id'], ['session_items.id'], name=op.f('fk_responses_session_item_id_session_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_responses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('progress_id', 'session_item_id', name=op.f('uq_responses_progress_id'))
    )
    op.create_index(op.f('ix_responses_session_item_id'), 'responses', ['session_item_id'], unique=False)
    op.create_index(op.f('ix_responses_user_id'), 'responses', ['user_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_session_summaries_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progress_id'], ['session_progress.id'], name=op.f('fk_session_summaries_progress_id_session_progress'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_summaries'))
    )
    op.create_index(op.f('ix_session_summaries_progress_id'), 'session_summaries', ['progress_id'], unique=False)
    op.create_table('xp_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('initial', 'quiz_correct', 'poll_correct', 'manual_adjustment', name='xp_reason'), nullable=False),
    sa.Column('session_item_id', sa.UUID(), nullable=True),
    sa.Column('response_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_xp_ledger_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_xp_ledger_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name=op.f('fk_xp_ledger_response_id_responses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_item_id'], ['session_items.id'], name=op.f('fk_xp_ledger_session_item_id_session_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_ledger'))
    )
    op.create_index('ix_xp_ledger_user_class', 'xp_ledger', ['user_id', 'class_id'], unique=False)
    op.create_index('uq_xp_ledger_user_class_initial', 'xp_ledger', ['user_id', 'class_id'], unique=True, postgresql_where=sa.text("reason = 'initial'"))
    op.create_index('uq_xp_ledger_user_item', 'xp_ledger', ['user_id', 'session_item_id'], unique=True, postgresql_where=sa.text('session_item_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_xp_ledger_user_item', table_name='xp_ledger', postgresql_where=sa.text('session_item_id IS NOT NULL'))
    op.drop_index('uq_xp_ledger_user_class_initial', table_name='xp_ledger', postgresql_where=sa.text("reason = 'initial'"))
    op.drop_index('ix_xp_ledger_user_class', table_name='xp_ledger')
    op.drop_table('xp_ledger')
    op.drop_index(op.f('ix_session_summaries_progress_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_responses_user_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_session_item_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_session_progress_session_id'), table_name='session_progress')
    op.drop_table('session_progress')
    op.drop_index(op.f('ix_live_runs_session_id'), table_name='live_runs')
    op.drop_table('live_runs')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_document_chunks_topic_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_content_requests_class_id'), table_name='content_requests')
    op.drop_table('content_requests')
    op.drop_table('content_documents')
    op.drop_index(op.f('ix_topics_class_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_agent_runs_agent'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_training_sessions_class_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_documents_class_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_class_members_user_id'), table_name='class_members')
    op.drop_table('class_members')
    op.drop_index(op.f('ix_class_access_codes_class_id'), table_name='class_access_codes')
    op.drop_table('class_access_codes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_classes_trainer_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('uq_model_versions_active', table_name='model_versions', postgresql_where=sa.text('is_active'))
    op.drop_table('model_versions')
    # ### end Alembic commands ###
    for name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {name}")
